# Generated by Django 4.1.4 on 2023-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
